### ISSUE TITLE
Develop edge detecion block for read gpio

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/intel_mraa#5]
http://iotdk.intel.com/docs/master/mraa/python/mraa.html#mraa.Gpio.edge

Similar to MonitorGPIO on a raspi, we would like edge detection on this device. If the library supports it it gives us much improved response time and lower cpu overhead.

**Comment by hansmosh** [comment]
Created the block on the interrupt branch. Need to add unit tests still
